### ISSUE TITLE
idea on project

### ISSUE THREAD

**Issue by Guilherme-Chinaglia** [doesangueorg/doesangueorg.github.io#8]
I don't know if it's going to be part of the project, but i was looking some site of blood donation, and one of them, catched my attention, [Hemosc](http://www.hemosc.org.br/). On the top right part of the site, there is a statistic with the quantity of blood that they have. Maybe you can try to implement this but split in bank of blood.

**Comment by JoseCage** [comment]
@Guilherme-Chinaglia this feature is so fine. But let me understand, **HEMOSC** is like a blood bank, right? 

One of big features i want to add is  "stock management" for **blood banks** but i don't know if we can do it now..

Pay attention: this repo is for [landing page](https://doesangue.me) only, i think this implementation sounds better in [webapp](https://github.com/doesangueorg/doesangue-webapp)


![screenshot-www hemosc org br-2017-10-27-14-28-44-338](https://user-images.githubusercontent.com/4200487/32106411-76a7bbd6-bb23-11e7-846d-d5a1a4328187.png)

**Comment by Guilherme-Chinaglia** [comment]
sorry, about the wrong repository, certainly it's better in [webapp](https://github.com/doesangueorg/doesangue-webapp)

**Comment by JoseCage** [comment]
No problem @Guilherme-Chinaglia Thanks for your suggestion anyway.. I will add this **Feature** to my future plans for sure..
